export class DataField {
    readonly name: string;
    readonly type: string;
    readonly line: number;

    constructor(name: string, type: string, line: number) {
        this.name = name;
        this.type = type;
        this.line = line;
    }
}

const WHITESPACE_CHARS = new Set([
    ' ',  // space
    '\t', // tab
    '\n', // newline
]);

const ASCII_WORD_CHARS = new Set(
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_'
);

export function parseDataFields(source: string): DataField[] {
    const dataFieldAttribute = "DataField";

    const dataFields: DataField[] = [];
    const lines = source.split('\n');
    let lineIndex = 0;
    search: while (lineIndex < lines.length) {
        let line = lines[lineIndex];
        const leftAttributeListBracketIndex = line.indexOf('[');
        const dataFieldAttributeIndex = line.indexOf(dataFieldAttribute);
        const rightAttributeListBracketIndex = line.lastIndexOf(']');
        let dataFieldName: string | undefined;
        let dataFieldFound = false;
        parseDataFieldAttribute: {
            // search for pattern: `[...DataField...]`
            if (0 <= leftAttributeListBracketIndex && leftAttributeListBracketIndex <= dataFieldAttributeIndex && dataFieldAttributeIndex <= rightAttributeListBracketIndex) {
                // find datafield attribute params
                const leftDataFieldParaIndex = dataFieldAttributeIndex + dataFieldAttribute.length;
                if (line.charAt(leftDataFieldParaIndex) !== '(') {
                    // datafield name is autogenerated from field name
                    dataFieldFound = true;
                    break parseDataFieldAttribute;
                }
                let paraLevel = 1;
                let charIndex = leftDataFieldParaIndex;
                while (paraLevel > 0) {
                    charIndex += 1
                    if (charIndex >= line.length) {
                        // have not found closing para: out of characters
                        break parseDataFieldAttribute;
                    }
                    switch (line.charAt(charIndex)) {
                        case '(':
                            paraLevel += 1;
                            break;
                        case ')':
                            paraLevel -= 1;
                            break;
                    }
                }
                if (paraLevel != 0) {
                    // no closing para
                    break parseDataFieldAttribute;
                }
                // search for pattern: `[...DataField(..."..."...)...]`
                const rightDataFieldParaIndex = charIndex;
                const leftDataFieldNameIndex = line.indexOf('"');
                if (leftDataFieldNameIndex <= leftDataFieldParaIndex || leftDataFieldNameIndex >= rightDataFieldParaIndex) {
                    // datafield name is autogenerated from field name
                    dataFieldFound = true;
                    break parseDataFieldAttribute;
                }
                const rightDataFieldNameIndex = line.indexOf('"', leftDataFieldNameIndex + 1);
                if (rightDataFieldNameIndex <= leftDataFieldParaIndex || rightDataFieldNameIndex >= rightDataFieldParaIndex) {
                    // invalid name string
                    break parseDataFieldAttribute;
                }
                dataFieldName = line.substring(leftDataFieldNameIndex + 1, rightDataFieldNameIndex);
                dataFieldFound = true;
            }
        }
        if (!dataFieldFound) {
            lineIndex += 1;
            continue search;
        }
        // now we need to find the class field itself
        // searching for pattern: `...public ...` or `...private ...` and etc.
        // should end with whitespace!
        const classFieldStartKeywords = ["public ", "internal ", "private ", "protected ", "readonly "];
        parseClassField: {
            let keyword: string = "";
            let keywordIndex = -1;
            findClassField: while (lineIndex < lines.length) {
                line = lines[lineIndex];
                for (const k of classFieldStartKeywords) {
                    keyword = k;
                    keywordIndex = line.indexOf(keyword);
                    if (keywordIndex >= 0) {
                        break findClassField;
                    }
                }
                lineIndex += 1;
            }
            if (keywordIndex < 0) {
                // class field not found
                break parseClassField;
            }

            // now we need to find the type, its either a simple 'word' (e.g. bool), or a generic (e.g. Dictionary<...>)
            // for generics we need to find the closing '>' para
            let charIndex = keywordIndex + (keyword.length - 1); // ignore whitespace in the end
            while (WHITESPACE_CHARS.has(line.charAt(charIndex))) {
                charIndex += 1;
                if (charIndex >= line.length) {
                    break parseClassField;
                }
            }
            const leftTypeIndex = charIndex;
            while (true) {
                charIndex += 1;
                if (charIndex >= line.length) {
                    break parseClassField;
                }
                const ch = line.charAt(charIndex);
                if (WHITESPACE_CHARS.has(ch)) {
                    // found the end of type string, backtrack to last character
                    charIndex -= 1;
                    break;
                }
                if (ch === '<') {
                    let paraLevel = 1;
                    while (paraLevel > 0) {
                        charIndex += 1
                        if (charIndex >= line.length) {
                            // have not found closing para: out of characters
                            break parseClassField;
                        }
                        switch (line.charAt(charIndex)) {
                            case '<':
                                paraLevel += 1;
                                break;
                            case '>':
                                paraLevel -= 1;
                                break;
                        }
                    }
                    if (paraLevel != 0) {
                        // no closing para
                        break parseClassField;
                    }
                    // need to handle nullable types, e.g. 'List<string>?'
                    if (charIndex + 1 < line.length && !WHITESPACE_CHARS.has(line.charAt(charIndex + 1))) {
                        charIndex += 1
                    }
                    break;
                }
            }
            const rightTypeIndex = charIndex;

            // now find the field name if necessary, should be simple?
            if (dataFieldName === undefined) {
                // set the index right after type string end
                charIndex += 1;
                if (charIndex >= line.length) {
                    break parseClassField;
                }
                // skip all whitespaces
                while (WHITESPACE_CHARS.has(line.charAt(charIndex))) {
                    charIndex += 1;
                    if (charIndex >= line.length) {
                        break parseClassField;
                    }
                }
                const leftNameIndex = charIndex;
                while (true) {
                    charIndex += 1;
                    if (charIndex >= line.length) {
                        break parseClassField;
                    }
                    if (!ASCII_WORD_CHARS.has(line.charAt(charIndex))) {
                        // found the end of name string, backtrack to last character
                        charIndex -= 1;
                        break;
                    }
                }
                const rightNameIndex = charIndex;
                dataFieldName = line.substring(leftNameIndex, rightNameIndex + 1);
                // camel case
                dataFieldName = dataFieldName[0].toLowerCase() + dataFieldName.substring(1);
            }
            const typeName = line.substring(leftTypeIndex, rightTypeIndex + 1);
            dataFields.push(new DataField(dataFieldName, typeName, lineIndex + 1));
            break parseClassField;
        }
        lineIndex += 1
    }
    return dataFields;
}
